### ISSUE TITLE
Graph uses radians instead of degrees based on text

### ISSUE THREAD

**Issue by SquidXTV** [gsayson/h3-mathematics-2025#2]
# About
In `4.2 APPROXIMATING LIMITS` the text says this:
> Consider the function `f (x) = sin(x)/x` , where x is in degrees. If we graph it, we get:

The corresponding graph looks like this:
![graph](https://github.com/gsayson/h3-mathematics-2025/assets/88111627/271bbedf-cd9d-463d-b57b-45a14ce97cc5)

This graph doesn't match with the description "where x is in degrees", because the plot is using x in radians.

**Comment by gsayson** [comment]
Oh yeah, I forgot to change that. Thanks ^_^
